DROP DATABASE IF EXISTS placement_db;
CREATE DATABASE placement_db;
USE placement_db;

CREATE TABLE ROLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    role_id INT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES ROLES(id) ON DELETE RESTRICT
);

CREATE TABLE LOGIN (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE PERMISSION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_id INT NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    FOREIGN KEY (role_id) REFERENCES ROLES(id) ON DELETE CASCADE
);

CREATE TABLE USER_PHONE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE STUDENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    dept VARCHAR(100),
    cgpa DECIMAL(4, 2),
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE COMPANY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    contact VARCHAR(100),
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE COLLEGE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE JOB (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    salary VARCHAR(50),
    vacancy INT NOT NULL CHECK (vacancy > 0),
    FOREIGN KEY (company_id) REFERENCES COMPANY(id) ON DELETE CASCADE
);

CREATE TABLE PLACEMENTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    job_id INT NOT NULL,
    status ENUM('Applied', 'Selected', 'Rejected') DEFAULT 'Applied',
    description TEXT,
    UNIQUE KEY unique_application (student_id, job_id),
    FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE,
    FOREIGN KEY (job_id) REFERENCES JOB(id) ON DELETE CASCADE
);

-- Initial Data Setup
INSERT INTO ROLES (id, role_name) VALUES (1, 'Admin');
INSERT INTO ROLES (id, role_name) VALUES (2, 'Student');
INSERT INTO ROLES (id, role_name) VALUES (3, 'Company');
